# Generated by Django 4.0.3 on 2022-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanfics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('min', 'min'), ('mid', 'mid'), ('max', 'max')], max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('Continue', 'Continue'), ('Сompleted', 'Сompleted'), ('Frozen', 'Frozen'), ('No chapter', 'No chapter')], max_length=50, null=True)),
                ('genre', models.CharField(choices=[('Genre1', 'Genre1'), ('Genre2', 'Genre2'), ('Genre3', 'Genre3')], max_length=50, null=True)),
            ],
        ),
    ]
