# Generated by Django 4.0.3 on 2022-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fanfics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Fantastic', 'Fantastic'), ('Detective', 'Detective'), ('Romantic', 'Romantic')], max_length=200, null=True)),
            ],
        ),
    ]
