# Generated by Django 4.0.3 on 2022-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfics',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fanfics',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
