# Generated by Django 4.0.3 on 2022-04-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fanfics_author_fanfics_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Humor', 'Humor'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Detective', 'Detective'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Histrical', 'Historical'), ('Tragedy', 'Tragedy')], max_length=50)),
            ],
            options={
                'ordering': ['genre'],
            },
        ),
        migrations.AlterModelOptions(
            name='fanfics',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='fanfics',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='fanfics',
            name='genre',
        ),
        migrations.AddField(
            model_name='fanfics',
            name='genre',
            field=models.ManyToManyField(blank=True, to='main.genre'),
        ),
    ]
