# Generated by Django 3.2.13 on 2022-05-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_genre_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
