# Generated by Django 3.2.13 on 2022-05-12 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_fanfics_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfics',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
