# Generated by Django 3.2.13 on 2022-05-22 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_fanfics_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfics',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fanfics',
            name='favorites',
            field=models.ManyToManyField(auto_created=True, blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
